version: "2"

services:
  app: 
    image: irdaislakhuafa/school-library:latest
    container_name: school-library
    restart: on-failure
    networks:
      - net_school-library
    ports:
      - 80:8080
    # env_file: 
    #   - ./server.env
networks:
  net_school-library: 
  