version: "2"

services:
  app: 
    image: irdaislakhuafa/school-library:latest
    container_name: school-library
    restart: on-failure
    networks:
      - net-school-library
    ports:
      - 80:8080
    env_file: 
      - ./app.env
networks:
  net-school-library: 
    name: net-school-library
  